# Generated by Django 5.1.4 on 2025-01-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='director2',
            field=models.CharField(default='Петров Петр', max_length=100, null=True, verbose_name='Укажите второго режисера'),
        ),
    ]
