# Generated by Django 5.1.4 on 2025-01-06 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0002_movies_director2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='director2',
        ),
    ]
