# Generated by Django 5.1.4 on 2025-01-09 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0003_remove_movies_director2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'фильм', 'verbose_name_plural': 'список фильмов'},
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('stars', models.CharField(choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], default='⭐⭐⭐⭐⭐', max_length=100)),
                ('reviews_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='tv_show.movies')),
            ],
        ),
    ]
