# Generated by Django 5.1.5 on 2025-01-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show', '0004_alter_movies_options_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_slide', models.ImageField(upload_to='slider/')),
            ],
        ),
    ]
